version: "3.9"

services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./data/mongo:/data/db
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

  redis:
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./data/redis:/data
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

  scheduler:
    image: ${HONEYBEE_IMAGE}
    command: honeybee scheduler
    environment:
      REDIS_URI: redis://:${REDIS_PASSWORD}@redis
    depends_on:
      - redis
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure

  worker:
    image: ${HONEYBEE_IMAGE}
    environment:
      REDIS_URI: redis://:${REDIS_PASSWORD}@redis
      MONGO_URI: mongodb://${MONGO_WORKER_USERNAME}:${MONGO_WORKER_PASSWORD}@mongo/vespa
      JOB_CONCURRENCY: ${JOB_CONCURRENCY}
    depends_on:
      - redis
      - mongo
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

networks:
  default:
    name: vespa
    external: true