version: "3.9"

services:
  mongo:
    image: mongo:4
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ${DATA_DIR:-./data}/mongo:/data/db
    ports:
      - "27017:27017"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure

  redis:
    image: redis:6-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    # volumes:
    #   - ${DATA_DIR:-./data}/redis:/data
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure

  scheduler:
    image: ${HONEYBEE_IMAGE}
    command: honeybee scheduler
    environment:
      REDIS_URI: redis://:${REDIS_PASSWORD}@redis
      JOB_CONCURRENCY: ${JOB_CONCURRENCY}
    depends_on:
      - redis
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure

  worker:
    image: ${HONEYBEE_IMAGE}
    environment:
      REDIS_URI: redis://:${REDIS_PASSWORD}@redis
      MONGO_URI: mongodb://${MONGO_WORKER_USERNAME}:${MONGO_WORKER_PASSWORD}@mongo/${MONGO_DATABASE}
      JOB_CONCURRENCY: ${JOB_CONCURRENCY}
      DEBUG: masterchat
    depends_on:
      - redis
      - mongo
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

networks:
  default:
    name: honeybee
    external: true
