version: "3.2"

services:
  db:
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db

  redis:
    restart: unless-stopped
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data

  scheduler:
    build: .
    image: pkg.uechi.io/vespa-honeybee
    restart: unless-stopped
    command: node ./lib/scheduler.js
    environment:
      REDIS_URI: redis://redis
    depends_on:
      - redis

  worker:
    image: pkg.uechi.io/vespa-honeybee
    restart: unless-stopped
    environment:
      REDIS_URI: ${REDIS_URI:-redis://redis}
      MONGO_URI: mongodb://${MONGO_WORKER_USERNAME}:${MONGO_WORKER_PASSWORD}@db/vespa
      JOB_CONCURRENCY: 100
    depends_on:
      - redis
      - db
