version: "3.2"

services:
  db:
    image: mongo:4
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data

  scheduler:
    build: .
    image: ${HONEYBEE_IMAGE}
    command: honeybee scheduler
    environment:
      REDIS_URI: redis://redis
      JOB_CONCURRENCY: ${JOB_CONCURRENCY:-3}
    volumes:
      - "./lib:/app/lib"
      - "./node_modules:/app/node_modules"
    depends_on:
      - redis

  worker:
    image: ${HONEYBEE_IMAGE}
    environment:
      REDIS_URI: redis://redis
      MONGO_URI: mongodb://db/honeybee
      JOB_CONCURRENCY: ${JOB_CONCURRENCY:-3}
    volumes:
      - "./lib:/app/lib"
      - "./node_modules:/app/node_modules"
    depends_on:
      - redis
      - db
