version: "3.2"

services:
  db:
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "43205:27017"
    volumes:
      - ./data/mongo:/data/db
    deploy:
      placement:
        constraints: [node.role == manager]

  redis:
    restart: unless-stopped
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "32893:6379"
    volumes:
      - ./data/redis:/data
    deploy:
      placement:
        constraints: [node.role == manager]

  scheduler:
    build: .
    image: pkg.uechi.io/vespa-honeybee
    restart: unless-stopped
    command: node ./lib/scheduler.js
    environment:
      REDIS_URI: redis://:${REDIS_PASSWORD}@redis
    depends_on:
      - redis
    deploy:
      placement:
        constraints: [node.role == manager]

  worker:
    image: pkg.uechi.io/vespa-honeybee
    restart: unless-stopped
    environment:
      REDIS_URI: redis://:${REDIS_PASSWORD}@redis
      MONGO_URI: mongodb://${MONGO_WORKER_USERNAME}:${MONGO_WORKER_PASSWORD}@db/vespa
      JOB_CONCURRENCY: ${JOB_CONCURRENCY:-100}
    depends_on:
      - redis
      - db
    deploy:
      replicas: 1
