version: "3"

services:
  db:
    image: mongo:5
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db

  redis:
    image: redis:6-alpine
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data

  scheduler:
    build: .
    image: ${HONEYBEE_IMAGE}
    command: honeybee scheduler
    environment:
      REDIS_URI: redis://redis
      JOB_CONCURRENCY: ${JOB_CONCURRENCY:-3}
      HOLODEX_MAX_UPCOMING_HOURS: ${HOLODEX_MAX_UPCOMING_HOURS:-0}
      HOLODEX_API_KEY: ${HOLODEX_API_KEY}
    volumes:
      - ${DATA_DIR:-./data}/cache:/cache
      - "./lib:/app/lib"
      - "./node_modules:/app/node_modules"
    depends_on:
      - redis

  worker:
    image: ${HONEYBEE_IMAGE}
    environment:
      REDIS_URI: redis://redis
      MONGO_URI: mongodb://db/honeybee
      JOB_CONCURRENCY: ${JOB_CONCURRENCY:-3}
      DEBUG: masterchat
    volumes:
      - "./lib:/app/lib"
      - "./node_modules:/app/node_modules"
    depends_on:
      - redis
      - db
