apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    app: db
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  type: NodePort
  selector:
    app: db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-statefulset
  labels:
    app: db
spec:
  serviceName: db-service
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - image: mongo:5
          name: db
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: db-pvc
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: password
          resources: {}
      restartPolicy: Always
      volumes:
        - name: db-pvc
          persistentVolumeClaim:
            claimName: db-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pvc
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/db
